isBuildError: Use local variable
Diff is quite large but apart from using isBuildError instead of
"threadInfo == null", it's all whitespace/formatting.